core/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name='core'

urlpatterns = [

    path('signup/', views.signup, name='signup'),
    path('login/',  LoginView.as_view(template_name='core/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name= 'core/logged_out.html'),{'next_page': '/'}, name='logout'),
    path('Booking/', views.Bookingview, name='Booking'),
    path('message/<int:user2id>/', views.messageview, name='message'),
    path('profile/', views.profile, name='profile'),
    path('allBookings/',views.AllBookingsListView.as_view(),name='allBookings'),
    path('myBookings/',views.MyBookingsListView,name='myBookings'),
    path('mydoneBookings/',views.MydoneBookingsListView,name='mydoneBookings'),
    path('mydoneBookings/unbooked/<int:Booking_id>/',views.unbooked,name='unbooked'),
    path('myBookings/Bookingsuggestions/<int:Booking_id>/',views.detail,name='Bookingsuggestions'),
    path('myBookings/booked/<int:Booking_id>/',views.booked,name='booked'),
    path('myBookings/delete/<int:Booking_id>/',views.deleteBooking,name='myBookingsdelete'),
    path('mydoneBookings/delete/<int:Booking_id>/',views.deleteBooking,name='mydoneBookingsdelete'),
    path('myBookings/changeBooking/<pk>/',views.changeBooking.as_view(),name='changeBooking'),
    path('profile/changepassword/',views.change_password, name='change_password'),

    path('inbox/',views.inbox,name='inbox'),
    path('outbox/',views.outbox,name='outbox'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import url, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
     path('core/',include('core.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.exceptions import ValidationError
from PIL import Image

GENDER_CHOICES =(
    (1, "only male"),
    (2, "only female"),
    (0, "no specific choice")

)

# Create your models here.
def validate_luggage(value):
    if  (value<20):
        return value
    else:
        raise ValidationError("luggage is exceeded")


def validate_people(value):
    if  (value<4):
        return value
    else:
        raise ValidationError("persons are exceeded")


class Booking(models.Model):
    user =  models.ForeignKey(settings.AUTH_USER_MODEL,default=1,on_delete=models.CASCADE)
    created_by=models.CharField(max_length=50)
    pick_up_point=models.CharField(max_length=250)
    destination=models.CharField(max_length=250)
    booked = models.BooleanField(default=False)
    date=models.DateField()
    time=models.TimeField()
    window_for_pickup_time=models.DurationField()
    ammount_of_luggage=models.IntegerField(validators =[validate_luggage], default=0)
    number_of_people=models.IntegerField(validators =[validate_people], default=1)
    def get_absolute_url(self):
        return reverse('core:myBookings')
    def __str__(self):
        return self.pick_up_point+'-'+self.destination+'-'+str(self.booked)+'-'+str(self.id)
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class Message(models.Model):
     sender =  models.ForeignKey(settings.AUTH_USER_MODEL,default=1,on_delete=models.CASCADE)
     reciever = models.ForeignKey(User,on_delete=models.CASCADE, related_name="reciever")
     msg_content = models.CharField(max_length=10000)
    # created_at = models.CharField(max_length=1000)
     def __str__(self):
         return self.sender.username+'-'+self.reciever.username

     def save(self, *args, **kwargs):
         super().save(*args, **kwargs)




class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='default.jpg',upload_to='profile_pics')
    def __str__(self):
        return self.user.username

    def save(self,**kwargs):
        super().save()

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.forms import ModelForm
from core.models import Booking,Profile,Message



class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )




class BookingForm(ModelForm):
    class Meta:
        model = Booking
        exclude = ['user','booked']

class messageForm(ModelForm):
    class Meta:
        model = Message
        exclude = ['sender','reciever']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']



class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

core/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect,get_object_or_404
from django.urls import reverse
from django.contrib import messages
from .forms import SignUpForm
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from .forms import BookingForm,UserUpdateForm,ProfileUpdateForm,messageForm
from .models import Booking,Message
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('core:profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'core/change_password.html', {
        'form': form
    })



def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(reverse('core:login'))
    else:
        form = SignUpForm()
    return render(request, 'core/signup.html', {'form': form})

def profile(request):
    if request.method == 'POST':
        u_form=UserUpdateForm(request.POST,instance=request.user)
        p_form=ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,f'Your account has been updated!')
            return redirect('core:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'core/profile.html',context)

def Bookingview(request):

    if  request.method == 'POST':
        form=BookingForm(request.POST)


        if form.is_valid():
            instance=form.save(commit=False)
            instance.user=request.user
            instance.save()
            print(form.errors)
            messages.success(request,f'Your Booking has been saved!')
            return redirect('core:myBookings')
        else:
            print("Form is invalid")
    else:
        form=BookingForm()


    return render(request,'core/Booking.html',{'form':form})



def messageview(request,user2id):

    if  request.method == 'POST':
        form=messageForm(request.POST)


        if form.is_valid():
            instance=form.save(commit=False)
            instance.sender=request.user
            instance.reciever=User.objects.get(id=user2id)
            instance.save()
            print(form.errors)
            messages.success(request,f'Your message has sent')
            return redirect('core:myBookings')
        else:
            print("Form is invalid")
    else:
        form=messageForm()


    return render(request,'core/message.html',{'form':form})






class AllBookingsListView(ListView):
    model = Booking
    queryset = Booking.objects.all()
    template_name = 'core/allBookings_lv.html'

    #def get_queryset(self):
    #    return Booking.objects.filter(destination=self.request.user)

class changeBooking(UpdateView):
    model = Booking
    fields = ['pick_up_point','destination','booked']
    template_name = 'core/Booking.html'


def MyBookingsListView(request):
    a=Booking.objects.filter(user=request.user)
    b=Booking.objects.all()
    object_list=[]
    if (b and a):
        for c in b:
            if((not c.booked) and c.user==a[0].user ):
                object_list.append(c)
    return render(request,'core/myBookings_lv.html',{'object_list':object_list})

def MydoneBookingsListView(request):
    a=Booking.objects.filter(user=request.user)
    b=Booking.objects.all()
    object_list=[]
    if (b and a):
        for c in b:
            if((c.booked) and c.user==a[0].user ):
                object_list.append(c)
    return render(request,'core/mydoneBookings_lv.html',{'object_list':object_list})

def detail(request,Booking_id):
    a=Booking.objects.filter(id=Booking_id)
    b=Booking.objects.all()
    object_list=[]
    for c in b:
        if((not c.booked)and c.destination==a[0].destination and c.user!=a[0].user and c.pick_up_point==a[0].pick_up_point):
            object_list.append(c)
    return render(request,'core/suggestions_lv.html',{'object_list':object_list})


def booked(request,Booking_id):
    a=Booking.objects.get(id=Booking_id)
    a.booked=True
    a.save()
    return redirect('core:myBookings')


def inbox(request):
    a=Message.objects.filter(reciever=request.user)
    b=Message.objects.all().order_by('-id')
    object_list=[]
    if (b and a):
        for c in b:
            if(c.reciever==a[0].reciever ):
                object_list.append(c)
    return render(request,'core/inbox_lv.html',{'object_list':object_list})


def outbox(request):
    a=Message.objects.filter(sender=request.user)
    b=Message.objects.all().order_by('-id')
    object_list=[]
    if (b and a):
        for c in b:
            if(c.sender==a[0].sender ):
                object_list.append(c)
    return render(request,'core/outbox_lv.html',{'object_list':object_list})


def unbooked(request,Booking_id):
    a=Booking.objects.get(pk=Booking_id)
    a.booked=False
    a.save()
    return redirect('core:myBookings')

def deleteBooking(request,Booking_id):
    a=Booking.objects.get(pk=Booking_id)
    a.delete()
    return redirect('core:myBookings')

core/templates/core/Booking.html


{% extends 'core/base_Booking.html' %}}
{% load crispy_forms_tags %}

{% block title %}
Create Booking
{% endblock %}


{% block content %}
<br><br><br><br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">

      <h1>Create Booking</h1>
    </div>
    <div class="card-body text-center">
      <div class="container">
        <form enctype="multipart/form-data" method="post">
          {% csrf_token %}
          <div class="form-row ">
            {% for field in form %}
              <div class="form-group text-center col-md-6 mb-0">
                {{ field.label_tag }}<br>
                {{ field }}<br>
              </div>
            {% endfor %}
          </div>
          {% if field.help_text %}
          <small style="color: grey;">{{ field.help_text }}</small><br>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red;">{{ error }}</p><br>
          {% endfor %}
          <br>
          <div class="text-center">
            <button type="submit" class="btn btn-primary btn-lg">Submit</button>
          </div>
          <hr>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Cabsharing</title>
    {% load static %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <style>
            .toright {
                position: right;
            }
  </style>




  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">CS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="/core/profile/">Profile</a>
             </li>
             <li class="nav-item">
                <a class="nav-link" href="/core/Booking/">Add Booking</a>
              </li>
             <li class="nav-item">
               <a class="nav-link" href="{% url 'core:allBookings' %}">All Bookings</a>
             </li>
             <li class="nav-item">
               <a class="nav-link" href="{% url 'core:myBookings' %}">myBookings</a>
             </li>
             <li class="nav-item">
               <a class="nav-link" href="{% url 'core:mydoneBookings' %}">my done Bookings</a>
             </li>

          </ul>

        </div>
      </nav>



{% block content %}
{%endblock%}

  </body>
</html>

core/templates/core/base_Booking.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <!-- <link href="https://fonts.googleapis.com/css?family=Monoton&display=swap" rel="stylesheet"> -->

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" style="font-family:'Monoton', cursive; font-size:1.2em;" href="{% url 'core:myBookings' %}">CAB SHARING</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class='navbar-nav mx-auto'>
      <li class="nav-item active"><a class="nav-link" href="{% url 'core:Booking' %}">Create Booking</a></li>
      <li class="nav-item active"><a class="nav-link" href="{% url 'core:allBookings' %}">All Bookings</a></li>
      {% if user.is_authenticated %}
      <li class="nav-item active"><a class="nav-link" href="{% url 'core:myBookings' %}">My Bookings</a></li>
      <li class="nav-item active"><a class="nav-link" href="{% url 'core:mydoneBookings' %}">Completed Bookings</a></li>
      {% endif %}

    </ul>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'core:inbox'  %}">Inbox<span class="sr-only">(current)</span></a>
         </li>
         <li class="nav-item active">
             <a class="nav-link" href="{% url 'core:outbox'  %}">Outbox<span class="sr-only">(current)</span></a>
          </li>
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{request.user.username}}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'core:profile'  %}">Profile</a>
            <a class="dropdown-item" href="{% url 'core:change_password' %}">Change Password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'core:logout' %}">Logout</a>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'core:logout' %}">Logout<span class="sr-only">(current)</span></a>
        </li>

        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'core:login' %}">Login<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'core:signup' %}">Sign Up<span class="sr-only">(current)</span></a>
        </li>

        {% endif %}
      </ul>

    </div>
  </nav>

  {% block content %}
  {% endblock %}



  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>
<!-- font-family: 'Monoton', cursive; -->

core/templates/core/change_password.html
<form method="POST">
{{form.non_field_errors}}
{% csrf_token %}
{% for field in form %}
{{field.label_tag}}
{{ field }}
{{ field.help_text | safe }}
{% if field.errors %}
{{ field.errors }}
{% endif %}
{% endfor %}
<button type="submit">Submit</button>
</form>

core/templates/core/logged_out.html
{% extends 'core/base_accounts.html' %}
{% load crispy_forms_tags %}

{% block title %}
logged_out
{% endblock %}


{% block content %}
<br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">

      <h1>You are succesfully logged out </h1>
    </div>
    <div class="card-body">

      <div class="container text-center">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <br>
              <a class="btn btn-primary" href="{% url 'core:login'  %}" role="button">Go to Login Page</a>
            <p><strong>-- OR --</strong></p>
            <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
           <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a><br>
             <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
          </div>
          <br>
          <hr>
          <br>
          <p class='text-center'>Don't have an account yet? <a href="{% url 'core:signup' %}">SignUp</a></p>
        </form>
      </div>



    </div>
  </div>

</div>
<br><br><br>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base_accounts.html' %}
{% load crispy_forms_tags %}

{% block title %}
Login
{% endblock %}


{% block content %}
<br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">

      <h1>Login</h1>
    </div>
    <div class="card-body">

      <div class="container text-center">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          {% if field.help_text %}
          <small style="color:grey;">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color:red;">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <br><button type="submit" class="btn btn-success btn-lg">Login</button>
            <p><strong>-- OR --</strong></p>
            <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
           <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a><br>
             <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
          </div>
          <br>
          <hr>
          <br>
          <p class='text-center'>Don't have an account yet? <a href="{% url 'core:signup' %}">SignUp</a></p>
        </form>
      </div>



    </div>
  </div>

</div>
<br><br><br>
{% endblock %}

core/templates/core/message.html
{% extends 'core/base_Booking.html' %}}
{% load crispy_forms_tags %}

{% block title %}
Send Message
{% endblock %}


{% block content %}
<br><br><br><br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">

      <h1>Message</h1>
    </div>
    <div class="card-body">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form  }}

          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-success btn-lg">Send</button>
          </div>

        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/core/myBookings_lv.html


{% extends 'core/base_Booking.html' %}

{% block title %}
My Bookings
{% endblock %}

{% block content %}


<br><br><br>

<div class="text-center">
  <h1>My Bookings</h1>
</div>

{% if messages %}
{% for message in messages %}
<div class="container ">
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
{% endfor %}
{% endif %}

<br><br>
<div class="col-lg-12 text-center" style='padding-left: 50px;padding-right: 50px; '>

  <div class="container text-center">
    <div class="row">
      <div class="card-group ">
        <!-- <div class="col-md-4"> -->

  {%if object_list%}
        {% for Booking in object_list %}

        <div class="col-lg-6 col-md-6">

          <!-- {% if user.is_member %}
          sjfhskjhf
          {% endif %}
          {% if request.user in Booking.members.all %}
          hahahahahah
          {% endif %} -->


          <div class="card text-white border-secondary mx-auto mb-5 w-100" style='background-color:rgb(23, 38, 87); '>


              <div class="card-body" style='border: 1px solid rgb(23, 38, 87) '>
                <div class="card-title text-center">

                </div>
                <div class="card-text">
                  <h6>Booking Id : {{Booking.id}}</h6>
                  <h6>From : {{Booking.pick_up_point}}</h6>
                  <h6>To : {{Booking.destination}}</h6>
                  <h6>created by : {{Booking.created_by}}</h6>
                  <h6>user : {{Booking.user.username}}</h6>
                  <h6>Date : {{Booking.date}}</h6>
                  <h6>Time : {{Booking.time}}</h6>
                  <h6>user : {{Booking.user.username}}</h6>
                  <h6>Window for pickup time: {{Booking.window_for_pickup_time}}</h6>
                  <h6>Ammount of luggage: {{Booking.ammount_of_luggage}}</h6>
                  <h6>Number of People: {{Booking.number_of_people}}</h6>

                  <br>
                  <div class="card-link">

                    <a href="{% url 'core:Bookingsuggestions' Booking.pk %}" class='btn btn-primary btn-sm '>suggestions</a>

                    <a href="{% url 'core:changeBooking' Booking.pk %}" class='btn btn-warning btn-sm '>Edit</a>
                    <a href="{% url 'core:myBookingsdelete' Booking.pk %}" class='btn btn-danger btn-sm '>Delete</a>

                    <a href="{% url 'core:booked' Booking.pk %}" class='btn btn-danger btn-sm '>made this Booking</a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {% endfor %}
{%else%}
  <h1 class='mt-5' style="text-align:center; color:#00796b;" id='no_Booking'>No Bookings</h1>
{%endif%}

          </div>
        </div>
      </div>


    </div>


{% endblock %}

core/templates/core/profile.html


{% extends 'core/base_user.html' %}

{% load crispy_forms_tags %}
{% block title %}
Profile
{% endblock %}


{% block content %}
<br><br><br><br>
<div class="container">
  <div class="card mx-auto" style='width: 30rem;'>
    <img class='card-img-top  '  style='height:15rem; width: 30rem;' src="{{ user.profile.image.url }}" alt="none">
    <div class="card-img-overlay">

    </div>
    <div class="card-body">
      <div class="card-title text-center">
        <h2>{{user.username}}</h2>
        <h2>{{ user.email }}</h2>
      </div>
      <div class="card-text">
        <h6>Email: {{user.email}}</h6>
        <br>
        </div>


    </div>
  </div>
  <br>



  <div class="container">
    <div class="card">
      <div class="card-header text-center">

        <h1>Profile Info</h1>
      </div>

      <div class="card-body text-center">
        <div class="container">
          <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              {{ u_form |crispy  }}<br>
              {{ p_form |crispy }}<br>
          </fieldset>
          <div class="form-group">
            <a class="btn btn-primary" href="{%url 'core:change_password'%}" role="button">change password</a>

              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>


        </div>
      </div>
    </div>
  </div>




</div>
{% endblock %}